package com.hubspot.jinjava.interpret;


public enum TemplateErrorCategory {
  BLOG_NOT_FOUND_BY_ID,
  BLOG_INVALID_PARAMETERS,
  IMPORT_CYCLE_DETECTED,
  INVALID_CONVERT_RGB_COLOR,
  INVALID_COLOR_VARIANT_RGB_COLOR,
  MISSING_RESOURCE,
  MISSING_TEMPLATE,
  UNKNOWN_EMBED_TYPE,
  UNKNOWN
}
