package com.hubspot.jinjava.features;

public interface BuiltInFeatures {
  String WHITESPACE_REQUIRED_WITHIN_TOKENS = "whitespace_required_within_tokens";
  String FIXED_DATE_TIME_FILTER_NULL_ARG = "FIXED_DATE_TIME_FILTER_NULL_ARG";
  String ECHO_UNDEFINED = "echoUndefined";
  String PREVENT_ACCIDENTAL_EXPRESSIONS = "PREVENT_ACCIDENTAL_EXPRESSIONS";
  String IGNORE_NESTED_INTERPRETATION_PARSE_ERRORS =
    "IGNORE_NESTED_INTERPRETATION_PARSE_ERRORS";
  String OUTPUT_UNDEFINED_VARIABLES_ERROR = "OUTPUT_UNDEFINED_VARIABLES_ERROR";
}
