name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: jdk-${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: "Build"
        run: mvn --batch-mode -no-transfer-progress -V verify
        env:
          JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED
